PYTHON_INCLUDE=/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7


all: PeptideFragmentSingleton.so

# build my C library
libpeptidefragmentsingleton.so: peptide_fragment.o compute_pI.o 
	gcc -shared -lstdc++ -o libpeptidefragmentsingleton.so peptide_fragment.o compute_pI.o 
peptide_fragment.o: peptide_fragment.hpp peptide_fragment.cpp
	gcc -g -fPIC -c -o peptide_fragment.o peptide_fragment.cpp
compute_pI.o: compute_pI.c
	gcc -fPIC -c -o compute_pI.o compute_pI.c

# generate the binding code
peptide_fragment-binding.cpp: peptide_fragment.hpp peptide_fragment.py
	PYTHONPATH=$$PYTHONPATH python peptide_fragment.py > peptide_fragment-binding.cpp

# build the binding code
peptide_fragment-binding.o: peptide_fragment-binding.cpp
	gcc -fPIC -I$(PYTHON_INCLUDE) -c -o peptide_fragment-binding.o peptide_fragment-binding.cpp

# build the final python module
PeptideFragmentSingleton.so: libpeptidefragmentsingleton.so peptide_fragment-binding.o compute_pI.o  
	gcc -shared -lstdc++ -o PeptideFragmentSingleton.so -L. -lpeptidefragmentsingleton -framework Python peptide_fragment-binding.o compute_pI.o


clean:
	rm -f *.o *.so *.gch peptide_fragment-binding.cpp *~ 2>/dev/null
