# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Digest-Perl-MD5
version:      1.8
version_from: ./lib/Digest/Perl/MD5.pm
installdirs:  site
requires:
    Exporter:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
